[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py check && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn CVProject.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level debug --preload"
# healthcheckPath = "/health/"
# healthcheckTimeout = 600
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.11"
