[build]
builder = "nixpacks"

[deploy]
startCommand = "python startup_check.py && python manage.py check --verbosity=2"
# healthcheckPath = "/health/"
# healthcheckTimeout = 600
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.11"
