[build]
builder = "nixpacks"

[deploy]
startCommand = "python railway_startup.py"
# healthcheckPath = "/health/"
# healthcheckTimeout = 600
restartPolicyType = "on_failure"

[deploy.envs]
PYTHON_VERSION = "3.11"
