# Generated by Django 5.2.5 on 2025-08-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('skills', models.TextField(help_text='List your technical and soft skills', verbose_name='Skills')),
                ('projects', models.TextField(help_text='Describe your key projects and achievements', verbose_name='Projects')),
                ('bio', models.TextField(help_text='Professional summary and background', verbose_name='Bio')),
                ('contacts', models.TextField(help_text='Email, phone, LinkedIn, etc.', verbose_name='Contact Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-created_at'],
            },
        ),
    ]
