# Generated by Django 5.2.5 on 2025-08-07 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP Method')),
                ('path', models.CharField(max_length=255, verbose_name='Request Path')),
                ('query_string', models.TextField(blank=True, verbose_name='Query String')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='Remote IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('response_status', models.IntegerField(verbose_name='Response Status')),
                ('response_time', models.FloatField(verbose_name='Response Time (seconds)')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Is Authenticated')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='main_reques_timesta_21179b_idx'), models.Index(fields=['method'], name='main_reques_method_b16918_idx'), models.Index(fields=['path'], name='main_reques_path_21c140_idx'), models.Index(fields=['response_status'], name='main_reques_respons_4720be_idx')],
            },
        ),
    ]
